import { SourceType } from "@/lib/actions/voice-cache";
import { parseSegments } from "@/lib/utils/stage-directions";
import { ScriptLine } from "@/lib/types";

type PreloadProgressCallback = (completed: number, total: number) => void;

/**
 * AudioQueue v2 — Pre-vocalized only
 * 
 * All audio is pre-generated by /api/vocalize and stored in Supabase Storage.
 * This queue only handles URL construction and browser-level preloading.
 * NO live TTS generation. If audio is missing → returns null (caller handles fallback).
 */
export class AudioQueue {
    /**
     * Browser-level preload cache: maps URL → fetch promise.
     * Warming the browser cache ensures instant playback.
     */
    private preloadCache = new Map<string, Promise<boolean>>();
    private maxCacheSize = 100;

    constructor() { }

    /**
     * Build the direct Supabase Storage URL for a pre-vocalized audio segment.
     * Format: audio_cache/{sourceId}/{lineId}_{segmentIndex}.mp3
     */
    public getDirectUrl(sourceId: string, lineId: string, segmentIndex: number): string {
        const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
        return `${supabaseUrl}/storage/v1/object/public/audio_cache/${sourceId}/${lineId}_${segmentIndex}.mp3`;
    }

    /**
     * Get URL for a specific segment. Only returns direct Supabase URLs.
     * Returns null if lineId/segmentIndex are missing (audio not available).
     */
    public getUrl(
        _text: string,
        _character: string,
        _lineIndex: number,
        _sourceType: SourceType,
        sourceId: string,
        _troupeId?: string,
        _isDirection: boolean = false,
        lineId?: string,
        segmentIndex?: number
    ): string | null {
        if (lineId && segmentIndex !== undefined) {
            return this.getDirectUrl(sourceId, lineId, segmentIndex);
        }

        // No lineId = audio not available (old script without line IDs)
        console.warn(`[AudioQueue] No lineId for line index ${_lineIndex} — audio not available. Re-vocalize this script.`);
        return null;
    }

    /**
     * Build the list of URLs that need preloading for a range of lines.
     */
    private buildPreloadUrls(
        lines: ScriptLine[],
        startingIndex: number,
        count: number,
        sourceId: string,
        showDirections: boolean
    ): string[] {
        const urls: string[] = [];

        for (let i = 0; i < count; i++) {
            const index = startingIndex + i;
            if (index >= lines.length) break;

            const line = lines[index];
            if (!line || !line.id) continue;

            const segments = parseSegments(line.text);

            if (!showDirections) {
                // When directions are hidden, vocalize merges all dialogue into segment 0
                const hasDialogue = segments.some(s => !s.isDirection && s.text.trim());
                if (hasDialogue) {
                    urls.push(this.getDirectUrl(sourceId, line.id, 0));
                }
            } else {
                // When directions are shown, each segment has its own file
                for (let segIdx = 0; segIdx < segments.length; segIdx++) {
                    if (!segments[segIdx].text.trim()) continue;
                    urls.push(this.getDirectUrl(sourceId, line.id, segIdx));
                }
            }
        }

        return urls;
    }

    /**
     * Pre-fetch audio files into browser cache for instant playback.
     * Uses HEAD requests first (cheap), then full GET for the buffer.
     */
    private async warmUrl(url: string): Promise<boolean> {
        try {
            const response = await fetch(url, { method: "GET" });
            return response.ok;
        } catch {
            return false;
        }
    }

    /**
     * Preload multiple lines (lookahead) — fire-and-forget.
     */
    public preload(
        lines: ScriptLine[],
        startingIndex: number,
        count: number,
        _sourceType: SourceType,
        sourceId: string,
        _troupeId: string | undefined,
        showDirections: boolean
    ) {
        const urls = this.buildPreloadUrls(lines, startingIndex, count, sourceId, showDirections);

        for (const url of urls) {
            if (!this.preloadCache.has(url)) {
                this.preloadCache.set(url, this.warmUrl(url));
            }
        }

        // Evict old entries
        if (this.preloadCache.size > this.maxCacheSize) {
            const keysToDelete = Array.from(this.preloadCache.keys()).slice(0, this.preloadCache.size - this.maxCacheSize);
            keysToDelete.forEach(k => this.preloadCache.delete(k));
        }
    }

    /**
     * Preload with progress tracking — used for initial buffering before playback starts.
     */
    public async preloadWithProgress(
        lines: ScriptLine[],
        startingIndex: number,
        count: number,
        _sourceType: SourceType,
        sourceId: string,
        _troupeId: string | undefined,
        showDirections: boolean,
        onProgress?: PreloadProgressCallback
    ): Promise<{ total: number; completed: number }> {
        const urls = this.buildPreloadUrls(lines, startingIndex, count, sourceId, showDirections);
        const total = urls.length;

        if (onProgress) onProgress(0, total);
        if (total === 0) return { total: 0, completed: 0 };

        let completed = 0;
        const promises = urls.map(async (url) => {
            if (!this.preloadCache.has(url)) {
                this.preloadCache.set(url, this.warmUrl(url));
            }
            try {
                await this.preloadCache.get(url);
            } finally {
                completed++;
                if (onProgress) onProgress(completed, total);
            }
        });

        await Promise.all(promises);
        return { total, completed };
    }

    public clear() {
        this.preloadCache.clear();
    }
}
