import { SourceType } from "@/lib/actions/voice-cache";
import { parseSegments } from "@/lib/utils/stage-directions";
import { ScriptLine } from "@/lib/types";
import { RehearsalAudioEngine } from "@/lib/audio/gapless-player";

type PreloadProgressCallback = (completed: number, total: number) => void;

/**
 * AudioQueue v2 — Pre-vocalized only
 * 
 * All audio is pre-generated by /api/vocalize and stored in Supabase Storage.
 * This queue only handles URL construction.
 * Preloading is delegated to the RehearsalAudioEngine.
 */
export class AudioQueue {
    private engine: RehearsalAudioEngine;

    constructor(engine: RehearsalAudioEngine) {
        this.engine = engine;
    }

    /**
     * Build the direct Supabase Storage URL for a pre-vocalized audio segment.
     * Format: audio_cache/{sourceId}/{lineId}_{segmentIndex}.mp3
     */
    public getDirectUrl(sourceId: string, lineId: string, segmentIndex: number): string {
        const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
        return `${supabaseUrl}/storage/v1/object/public/audio_cache/${sourceId}/${lineId}_${segmentIndex}.mp3`;
    }

    /**
     * Get URLs for a specific segment. Returns array of fallback URLs.
     * Starts with direct private URL, then falls back to original public URL.
     */
    public getUrls(
        _text: string,
        _character: string,
        _lineIndex: number,
        _sourceType: SourceType,
        sourceId: string,
        originalScriptId?: string,
        _troupeId?: string,
        _isDirection: boolean = false,
        lineId?: string,
        segmentIndex?: number
    ): string[] {
        if (lineId && segmentIndex !== undefined) {
            const urls = [this.getDirectUrl(sourceId, lineId, segmentIndex)];
            if (originalScriptId && originalScriptId !== sourceId) {
                urls.push(this.getDirectUrl(originalScriptId, lineId, segmentIndex));
            }
            return urls;
        }

        // No lineId = audio not available (old script without line IDs)
        console.warn(`[AudioQueue] No lineId for line index ${_lineIndex} — audio not available. Re-vocalize this script.`);
        return [];
    }

    /**
     * Build the list of URLs that need preloading for a range of lines.
     */
    private buildPreloadUrls(
        lines: ScriptLine[],
        startingIndex: number,
        count: number,
        sourceId: string,
        originalScriptId: string | undefined,
        showDirections: boolean
    ): string[][] {
        const urlsList: string[][] = [];

        for (let i = 0; i < count; i++) {
            const index = startingIndex + i;
            if (index >= lines.length) break;

            const line = lines[index];
            if (!line || !line.id) continue;

            const segments = parseSegments(line.text);

            if (!showDirections) {
                // When directions are hidden, vocalize merges all dialogue into segment 0
                const hasDialogue = segments.some(s => !s.isDirection && s.text.trim());
                if (hasDialogue) {
                    const fallbacks = [this.getDirectUrl(sourceId, line.id, 0)];
                    if (originalScriptId && originalScriptId !== sourceId) fallbacks.push(this.getDirectUrl(originalScriptId, line.id, 0));
                    urlsList.push(fallbacks);
                }
            } else {
                // When directions are shown, each segment has its own file
                for (let segIdx = 0; segIdx < segments.length; segIdx++) {
                    if (!segments[segIdx].text.trim()) continue;
                    const fallbacks = [this.getDirectUrl(sourceId, line.id, segIdx)];
                    if (originalScriptId && originalScriptId !== sourceId) fallbacks.push(this.getDirectUrl(originalScriptId, line.id, segIdx));
                    urlsList.push(fallbacks);
                }
            }
        }

        return urlsList;
    }

    /**
     * Preload multiple lines (lookahead) — fire-and-forget.
     */
    public preload(
        lines: ScriptLine[],
        startingIndex: number,
        count: number,
        _sourceType: SourceType,
        sourceId: string,
        originalScriptId: string | undefined,
        _troupeId: string | undefined,
        showDirections: boolean
    ) {
        const urlsList = this.buildPreloadUrls(lines, startingIndex, count, sourceId, originalScriptId, showDirections);
        this.engine.preloadBuffers(urlsList).catch(console.error);
    }

    /**
     * Preload with progress tracking — used for initial buffering before playback starts.
     */
    public async preloadWithProgress(
        lines: ScriptLine[],
        startingIndex: number,
        count: number,
        _sourceType: SourceType,
        sourceId: string,
        originalScriptId: string | undefined,
        _troupeId: string | undefined,
        showDirections: boolean,
        onProgress?: PreloadProgressCallback
    ): Promise<{ total: number; completed: number }> {
        const urlsList = this.buildPreloadUrls(lines, startingIndex, count, sourceId, originalScriptId, showDirections);
        const total = urlsList.length;

        if (onProgress) onProgress(0, total);
        if (total === 0) return { total: 0, completed: 0 };

        let completed = 0;
        const promises = urlsList.map(async (urls) => {
            try {
                await this.engine.loadAudio(urls);
            } finally {
                completed++;
                if (onProgress) onProgress(completed, total);
            }
        });

        await Promise.all(promises);
        return { total, completed };
    }

    public clear() {
        this.engine.clearCache();
    }
}
